version: '3'
services:
  api:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - PG_HOST=postgres

  worker:
    build: ./worker
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - PG_HOST=postgres

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_queue
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: