services:
  api:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=password
      - PG_DATABASE=task_queue
      - PG_PORT=5432

  worker:
    build: ./worker
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=password
      - PG_DATABASE=task_queue
      - PG_PORT=5432

  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    # Remove port mapping to avoid conflicts
    # ports:
    #   - "6379:6379"

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_queue
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task_queue"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: