global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules

scrape_configs:
  - job_name: 'task-api'
    static_configs:
      - targets: ['api:3000']
  - job_name: 'node'
    static_configs:
      - targets: ['api:3000', 'worker:3000']