# Use Node.js LTS
FROM node:18-alpine

WORKDIR /app

# COPY wait-for-it.sh ./
# RUN chmod +x wait-for-it.sh

COPY package*.json ./
RUN npm install

COPY . .

# Wait for Postgres/Redis, then start the worker
CMD ["node","worker.js"]

# CMD ["./wait-for-it.sh", "postgres:5432", "--", "node", "worker.js"]